// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using do_an_co_so.DataAccess;

#nullable disable

namespace do_an_co_so.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240530155646_InitialCreateIdentity")]
    partial class InitialCreateIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("do_an_co_so.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngaydang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tieude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("do_an_co_so.Models.DatTour", b =>
                {
                    b.Property<int>("IdDattour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDattour"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachsanMakhachsan")
                        .HasColumnType("int");

                    b.Property<int?>("Makhachsan")
                        .HasColumnType("int");

                    b.Property<int?>("Mapt")
                        .HasColumnType("int");

                    b.Property<int?>("Matour")
                        .HasColumnType("int");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tinhtrang")
                        .HasColumnType("int");

                    b.Property<int>("TourMaTour")
                        .HasColumnType("int");

                    b.Property<string>("Yeucau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDattour");

                    b.HasIndex("KhachsanMakhachsan");

                    b.HasIndex("TourMaTour");

                    b.ToTable("DatTours");
                });

            modelBuilder.Entity("do_an_co_so.Models.KhachSan", b =>
                {
                    b.Property<int>("Makhachsan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makhachsan"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dongia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenkhachsan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thongtinchitiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int");

                    b.HasKey("Makhachsan");

                    b.ToTable("Khachsans");
                });

            modelBuilder.Entity("do_an_co_so.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Mapt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapt"));

                    b.Property<int>("DatTourIdDattour")
                        .HasColumnType("int");

                    b.Property<string>("Tenpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mapt");

                    b.HasIndex("DatTourIdDattour");

                    b.ToTable("Phuongthucthanhtoans");
                });

            modelBuilder.Entity("do_an_co_so.Models.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<string>("Banggia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diadiemkhoihanh")
                        .HasColumnType("int");

                    b.Property<string>("Diemden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachSanMakhachsan")
                        .HasColumnType("int");

                    b.Property<string>("Lichtrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoiluong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thongtinlienquan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int");

                    b.HasKey("MaTour");

                    b.HasIndex("KhachSanMakhachsan");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("do_an_co_so.Models.DatTour", b =>
                {
                    b.HasOne("do_an_co_so.Models.KhachSan", "Khachsan")
                        .WithMany()
                        .HasForeignKey("KhachsanMakhachsan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("do_an_co_so.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourMaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachsan");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("do_an_co_so.Models.PhuongThucThanhToan", b =>
                {
                    b.HasOne("do_an_co_so.Models.DatTour", "DatTour")
                        .WithMany("Phuongthucthanhtoan")
                        .HasForeignKey("DatTourIdDattour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTour");
                });

            modelBuilder.Entity("do_an_co_so.Models.Tour", b =>
                {
                    b.HasOne("do_an_co_so.Models.KhachSan", null)
                        .WithMany("Tours")
                        .HasForeignKey("KhachSanMakhachsan");
                });

            modelBuilder.Entity("do_an_co_so.Models.DatTour", b =>
                {
                    b.Navigation("Phuongthucthanhtoan");
                });

            modelBuilder.Entity("do_an_co_so.Models.KhachSan", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
