// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using do_an_co_so.DataAccess;

#nullable disable

namespace do_an_co_so.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240529021945_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("do_an_co_so.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngaydang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tieude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("do_an_co_so.Models.DatTour", b =>
                {
                    b.Property<string>("IdDattour")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<string>("Makhachsan1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mapt")
                        .HasColumnType("int");

                    b.Property<string>("TenKh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tinhtrang")
                        .HasColumnType("int");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yeucau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDattour");

                    b.HasIndex("MaTour");

                    b.HasIndex("Makhachsan1");

                    b.HasIndex("Mapt");

                    b.ToTable("datTours");
                });

            modelBuilder.Entity("do_an_co_so.Models.Khachsan", b =>
                {
                    b.Property<string>("Makhachsan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dongia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenkhachsan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thongtinchitiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int");

                    b.Property<string>("images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Makhachsan");

                    b.ToTable("PKhachsans");
                });

            modelBuilder.Entity("do_an_co_so.Models.Phuongthucthanhtoan", b =>
                {
                    b.Property<int>("Mapt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapt"));

                    b.Property<string>("Tenpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mapt");

                    b.ToTable("phuongthucthanhtoans");
                });

            modelBuilder.Entity("do_an_co_so.Models.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<string>("Banggia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diadiemkhoihanh")
                        .HasColumnType("int");

                    b.Property<string>("Diemden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lichtrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoiluong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thongtinlienquan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int");

                    b.Property<string>("images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTour");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("do_an_co_so.Models.DatTour", b =>
                {
                    b.HasOne("do_an_co_so.Models.Tour", "Matour")
                        .WithMany()
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("do_an_co_so.Models.Khachsan", "Makhachsan")
                        .WithMany()
                        .HasForeignKey("Makhachsan1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("do_an_co_so.Models.Phuongthucthanhtoan", "mapt")
                        .WithMany()
                        .HasForeignKey("Mapt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makhachsan");

                    b.Navigation("Matour");

                    b.Navigation("mapt");
                });
#pragma warning restore 612, 618
        }
    }
}
